name: Bug Report
description: Create a bug report for the theme.
title: 'Bug Report: Issue Description'
body:
  - type: checkboxes
    id: check
    attributes:
      label: Did you look at other bug repoerts?
      description: 'Make sure you arnt making a duplicate bug report.'
      options:
        - label: 'I have checked other bug reports'
          required: true
  - type: checkboxes
    id: default-theme
    attributes:
      label: This bug report has nothing to do with Avatar Decorations not showing up?
      description: 'Make sure you have any Discord Official Avatar Decoration equipped first.'
      options:
        - label: 'I have a Discord Official Avatar Decoration equipped'
          required: true
  - type: textarea
    id: bug-description
    attributes:
      label: 'Describe The Bug'
      description: 'Please write a clear description of what the bug is.'
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: 'Reproduction Steps'
      description: 'How do you get this bug? Please walk us through it step by step.'
      value: |
        1.
        2.
        3.
        ...
      render: bash
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: 'Screenshots'
      description: 'If applicable, add screenshots to help explain and / or show your problem.'
      render: bash
  - type: textarea
    id: other
    attributes:
      label: 'Additional Context'
      description: 'Add any other context about the problem here, or leave blank.'
