name: Bug Report
description: Create a bug report for the theme.
title: 'Bug Report: Issue Description'
body:
  - type: checkboxes
    id: check
    attributes:
      label: Did you look at other bug reports?
      description: 'Make sure you arnt making a duplicate bug report.'
      options:
        - label: 'I have checked other bug reports'
          required: true
  - type: checkboxes
    id: known-issues
    attributes:
      label: This bug is not in /known-issues?
      description: 'Make sure you have read /known-issues before reporting.'
      options:
        - label: 'I have read the known issues and this bug is not in there'
          required: true
  - type: checkboxes
    id: this-theme
    attributes:
      label: This bug is caused by this theme and this theme only?
      description: 'Make sure to see if the bug is still there without your other themes.'
      options:
        - label: 'I am 100% sure it is this theme'
  - type: textarea
    id: bug-description
    attributes:
      label: 'Describe The Bug'
      description: 'Please write a clear description of what the bug is.'
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: 'Reproduction Steps'
      description: 'How do you get this bug? Please walk us through it step by step.'
      value: |
        1.
        2.
        3.
        ...
      render: bash
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: 'Screenshots'
      description: 'If applicable, add screenshots to help explain and / or show your problem.'
      render: bash
  - type: textarea
    id: other
    attributes:
      label: 'Additional Context'
      description: 'Add any other context about the problem here, or leave blank.'
